projectThreeGlobe/config/routes.rb
Rails.application.routes.draw do
  resources :continents

  root 'continents#index'

end

projectThreeGlobe/app/models/continent.rb
class Continent < ActiveRecord::Base
end

projectThreeGlobe/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

projectThreeGlobe/app/controllers/continents_controller.rb
class ContinentsController < ApplicationController
  before_action :set_continent, only: [:show, :edit, :update, :destroy]

  # GET /continents
  # GET /continents.json
  def index
    @continents = Continent.all
  end

  # GET /continents/1
  # GET /continents/1.json
  def show
  end

  # GET /continents/new
  def new
    @continent = Continent.new
  end

  # GET /continents/1/edit
  def edit
  end

  # POST /continents
  # POST /continents.json
  def create
    @continent = Continent.new(continent_params)

    respond_to do |format|
      if @continent.save
        format.html { redirect_to @continent, notice: 'Continent was successfully created.' }
        format.json { render :show, status: :created, location: @continent }
      else
        format.html { render :new }
        format.json { render json: @continent.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /continents/1
  # PATCH/PUT /continents/1.json
  def update
    respond_to do |format|
      if @continent.update(continent_params)
        format.html { redirect_to @continent, notice: 'Continent was successfully updated.' }
        format.json { render :show, status: :ok, location: @continent }
      else
        format.html { render :edit }
        format.json { render json: @continent.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /continents/1
  # DELETE /continents/1.json
  def destroy
    @continent.destroy
    respond_to do |format|
      format.html { redirect_to continents_url, notice: 'Continent was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_continent
      @continent = Continent.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def continent_params
      params.require(:continent).permit(:name, :image)
    end
end

projectThreeGlobe/app/helpers/application_helper.rb
module ApplicationHelper
end

projectThreeGlobe/app/helpers/continents_helper.rb
module ContinentsHelper
end

projectThreeGlobe/app/views/continents/_form.html.erb
<%= form_for(@continent) do |f| %>
  <% if @continent.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@continent.errors.count, "error") %> prohibited this continent from being saved:</h2>

      <ul>
      <% @continent.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.text_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

projectThreeGlobe/app/views/continents/edit.html.erb
<h1>Editing Continent</h1>

<%= render 'form' %>

<%= link_to 'Show', @continent %> |
<%= link_to 'Back', continents_path %>

projectThreeGlobe/app/views/continents/index.html.erb
<!-- <p id="notice"><%= notice %></p>

<h1>Listing Continents</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @continents.each do |continent| %>
      <tr>
        <td><%= continent.name %></td>
        <td><%= continent.image %></td>
        <td><%= link_to 'Show', continent %></td>
        <td><%= link_to 'Edit', edit_continent_path(continent) %></td>
        <td><%= link_to 'Destroy', continent, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Continent', new_continent_path %>
 -->

projectThreeGlobe/app/views/continents/new.html.erb
<h1>New Continent</h1>

<%= render 'form' %>

<%= link_to 'Back', continents_path %>

projectThreeGlobe/app/views/continents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @continent.name %>
</p>

<p>
  <strong>Image:</strong>
  <%= @continent.image %>
</p>

<%= link_to 'Edit', edit_continent_path(@continent) %> |
<%= link_to 'Back', continents_path %>

projectThreeGlobe/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ProjectThreeGlobe</title>
  <%= stylesheet_link_tag    'application', media: 'all'%>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<!-- <h1>Hello Globe</h1> -->


<%= yield %>


</body>
</html>